### ISSUE TITLE
Switch io_uring to direct I/O

### ISSUE THREAD

**Issue by penberg** [penberg/limbo#46]
We already have application-level page cache so let's just switch to direct I/O.

**Comment by ishanjain28** [comment]
hey @penberg By Direct I/O, Do you mean how it's implemented for Darwin and windows ?

**Comment by penberg** [comment]
No, I mean use `O_DIRECT` so that the kernel does not cache pages for us (we have our own userspace page cache).

**Comment by ishanjain28** [comment]
Hey, I tried to add `O_DIRECT` flag to `File::open` but it breaks IO and it stops reading the file after that.

```rust
ishan@emerald ~/h/o/limbo (iouring_direct)> RUST_BACKTRACE=1 ./target/debug/limbo testing/testing
.db 
thread 'main' panicked at core/storage.rs:68:9:
assertion failed: page_size >= 512
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:146:5
   3: <limbo_core::storage::FileStorage as limbo_core::storage::PageIO>::get
             at ./core/storage.rs:68:9
   4: limbo_core::storage::PageSource::get
             at ./core/storage.rs:35:9
   5: limbo_core::sqlite3_ondisk::begin_read_btree_page
             at ./core/sqlite3_ondisk.rs:246:5
   6: limbo_core::pager::Pager::read_page
             at ./core/pager.rs:138:9
   7: limbo_core::btree::BTreeCursor::get_next_record
             at ./core/btree.rs:62:24
   8: <limbo_core::btree::BTreeCursor as limbo_core::types::Cursor>::rewind
             at ./core/btree.rs:117:15
   9: limbo_core::vdbe::Program::step
             at ./core/vdbe.rs:258:27
  10: limbo_core::Statement::step
             at ./core/lib.rs:219:22
  11: limbo_core::Rows::next
             at ./core/lib.rs:262:9
  12: limbo_core::Database::open
             at ./core/lib.rs:67:23
  13: limbo_core::Database::open_file
             at ./core/lib.rs:44:9
  14: limbo::main
             at ./cli/main.rs:36:14
  15: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I setup a test program like this, 

```rust
use std::{
    fs::File,
    os::{fd::AsRawFd, unix::fs::OpenOptionsExt},
};

use io_uring::IoUring;

fn main() {
    let file = File::options()
        .read(true)
        .write(true)
        .custom_flags(libc::O_DIRECT)
        .open("./Cargo.lock")
        .expect("error in opening file");

    let mut ring = IoUring::new(128).expect("error in creating io_uring instance");

    let fd = io_uring::types::Fd(file.as_raw_fd());
    let mut buf = [0; 1024];

    let read_e = {
        io_uring::opcode::Read::new(fd, buf.as_mut_ptr(), buf.len() as _)
            .build()
            .user_data(0x42)
    };

    unsafe {
        ring.submission()
            .push(&read_e)
            .expect("submission queue is full");
    }

    ring.submit_and_wait(1).expect("error in submit_and_wait");

    while let Some(cqe) = ring.completion().next() {
        assert_eq!(cqe.user_data(), 0x42);
        println!("{:?}", cqe.result());
        assert!(cqe.result() >= 0)
    }

    println!("{}", String::from_utf8_lossy(&buf));
}
```
and `cqe.result()` yields `-22` error. I don't know what other change I need to make to make this work.

**Comment by penberg** [comment]
@ishanjain28 That result code 22 means `EINVAL`, which means we're probably violating some io_uring assumptions on how the file is set up and/or buffer size/alignment.

I think https://github.com/DataDog/glommio, for example, has support for io_uring with direct I/O so we could check that out. We can also try to ping @glommer here to see if he remembers what's needed.

**Comment by glommer** [comment]
My initial hunch is just that the user data is invalid. What flags are "0x42" ?

**Comment by ishanjain28** [comment]
@glommer `0x42` was just for testing and I copied it from an example

**Comment by ishanjain28** [comment]
It is an alignment issue, I am looking into a way to fix this in the project. 

My updated example which works fine with O_DIRECT now.

```rust
use std::{
    fs::File,
    os::{fd::AsRawFd, unix::fs::OpenOptionsExt},
};

use io_uring::IoUring;

#[repr(align(512))]
struct Aligned([u8; 1024]);

fn main() {
    let file = File::options()
        .read(true)
        .write(true)
        .custom_flags(libc::O_DIRECT)
        .open("./Cargo.lock")
        .expect("error in opening file");

    let mut ring = IoUring::new(128).expect("error in creating io_uring instance");

    let fd = io_uring::types::Fd(file.as_raw_fd());
    let mut buf = Aligned([0; 1024]);
    let buf: &mut [u8] = &mut buf.0;

    let read_e = {
        io_uring::opcode::Read::new(fd, buf.as_mut_ptr(), buf.len() as _)
            .build()
            .user_data(0x42)
    };

    unsafe {
        ring.submission()
            .push(&read_e)
            .expect("submission queue is full");
    }

    ring.submit_and_wait(1).expect("error in submit_and_wait");

    while let Some(cqe) = ring.completion().next() {
        assert_eq!(cqe.user_data(), 0x42);
        println!("{:?}", cqe.result());
        assert!(cqe.result() >= 0)
    }

    println!("{}", String::from_utf8_lossy(&buf));
}
```

Thanks for the tip @penberg

**Comment by ishanjain28** [comment]
I am not sure how to proceed here. In limbo, I checked the buf before read/write operations and it is aligned so maybe alignment is not the problem in the project like it was in my test/sample.

**Comment by penberg** [comment]
@ishanjain28 What is the difference in code with your example and Limbo?

**Comment by ishanjain28** [comment]
I managed to fix the bug, `submit_and_wait` needs to wait until 1 completion even than 0 completion events
