### ISSUE TITLE
`cargo bench` causes a panic

### ISSUE THREAD

**Issue by mfleming** [penberg/limbo#50]
Running `cargo bench` with rustc 1.75.0 shows:

```
Benchmarking limbo/Execute prepared statement: 'SELECT * FROM users LIMIT 1': Warming up for 3.0000 sthread 'main' panicked at core/benches/benchmark.rs:48:25:
internal error: entered unreachable code
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/panicking.rs:127:5
   3: criterion::bencher::Bencher<M>::iter
   4: <criterion::routine::Function<M,F,T> as criterion::routine::Routine<M,T>>::warm_up
   5: criterion::routine::Routine::sample
   6: criterion::analysis::common
   7: criterion::benchmark_group::BenchmarkGroup<M>::bench_function
   8: benchmark::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: bench failed, to rerun pass `-p limbo_core --bench benchmark`
```

**Comment by penberg** [comment]
@mfleming Can you run with `RUST_BACKTRACE=full`? Are you on Linux?

**Comment by mfleming** [comment]
> @mfleming Can you run with `RUST_BACKTRACE=full`? Are you on Linux?

Yep, running on Linux. Here's the full backtrace

```
Benchmarking limbo/Execute prepared statement: 'SELECT * FROM users LIMIT 1': Warming up for 3.0000 sthread 'main' panicked at core/benches/benchmark.rs:48:25:
internal error: entered unreachable code
stack backtrace:
   0:     0x61d75acfc7fb - std::backtrace_rs::backtrace::libunwind::trace::h59b05d333ef250f9
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x61d75acfc7fb - std::backtrace_rs::backtrace::trace_unsynchronized::hbad10f6c65416841
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x61d75acfc7fb - std::sys_common::backtrace::_print_fmt::hda4a67a10610ef78
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x61d75acfc7fb - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he8d8a3d249a948a2
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x61d75ad3eeb0 - core::fmt::rt::Argument::fmt::h507ca91fbb1ef494
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/fmt/rt.rs:142:9
   5:     0x61d75ad3eeb0 - core::fmt::write::h4d5f6025aa566322
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/fmt/mod.rs:1120:17
   6:     0x61d75acf023d - std::io::Write::write_fmt::h1b572fe055a121e6
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/io/mod.rs:1762:15
   7:     0x61d75acfc5e4 - std::sys_common::backtrace::_print::hcaa91a137f39fd45
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x61d75acfc5e4 - std::sys_common::backtrace::print::hdf91ee03271e5d94
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x61d75ad2355a - std::panicking::default_hook::{{closure}}::h59f1f95e0a9a0472
  10:     0x61d75ad231fd - std::panicking::default_hook::h731f67f92b204ede
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:292:9
  11:     0x61d75ad23978 - std::panicking::rust_panic_with_hook::hbcae08ba0ccf4c11
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:779:13
  12:     0x61d75acfcba9 - std::panicking::begin_panic_handler::{{closure}}::h9083954869cd1afa
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:649:13
  13:     0x61d75acfca16 - std::sys_common::backtrace::__rust_end_short_backtrace::hb8caade51576a0bc
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x61d75ad236a2 - rust_begin_unwind
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:645:5
  15:     0x61d75a990435 - core::panicking::panic_fmt::hef0307862026e6f9
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/panicking.rs:72:14
  16:     0x61d75a9904d3 - core::panicking::panic::hf516d800ede7db8c
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/panicking.rs:127:5
  17:     0x61d75a9b9b66 - criterion::bencher::Bencher<M>::iter::hc158835b38dac9ba
  18:     0x61d75a9a040e - <criterion::routine::Function<M,F,T> as criterion::routine::Routine<M,T>>::warm_up::hf28f7a4267da8c97
  19:     0x61d75a9a318f - criterion::routine::Routine::sample::h736ac3f59b08daff
  20:     0x61d75a9bbd6c - criterion::analysis::common::h2dc81c9b06a5e892
  21:     0x61d75a9d2169 - criterion::benchmark_group::BenchmarkGroup<M>::bench_function::h7f31062ff894cc4b
  22:     0x61d75a9b9f66 - benchmark::main::h3a1b5d93f95c9d2c
  23:     0x61d75a9c75c3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc69060ed8ae849ac
  24:     0x61d75a9c41c9 - std::rt::lang_start::{{closure}}::hd7467501b852c930
  25:     0x61d75ad23594 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h9504c37abfb6f513
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/ops/function.rs:284:13
  26:     0x61d75ad23594 - std::panicking::try::do_call::h4e8ae0d3fdaef5a1
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:552:40
  27:     0x61d75ad23594 - std::panicking::try::hd686c4fbf6e25a1e
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:516:19
  28:     0x61d75ad23594 - std::panic::catch_unwind::h6357f6a92a957bb2
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panic.rs:142:14
  29:     0x61d75ad23594 - std::rt::lang_start_internal::{{closure}}::h6e901a66b8cf246f
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/rt.rs:148:48
  30:     0x61d75ad23594 - std::panicking::try::do_call::h7474622977779c90
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:552:40
  31:     0x61d75ad23594 - std::panicking::try::h88d686af4e2ea353
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panicking.rs:516:19
  32:     0x61d75ad0afcb - std::panic::catch_unwind::h602261075d2dc6e5
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/panic.rs:142:14
  33:     0x61d75ad0afcb - std::rt::lang_start_internal::hea207582130b429d
                               at /build/rustc-kAv1jW/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/rt.rs:148:20
  34:     0x61d75a9c41be - std::rt::lang_start::h868789f5aa6a9532
  35:     0x7a9797029d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  36:     0x7a9797029e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  37:     0x61d75a990da5 - _start
  38:                0x0 - <unknown>
```
